platform :ios, '8.0'

source 'http://gitlab.bbwc.cn/pods/slatespecs.git'
source 'http://gitlab.bbwc.cn/pods/Specs.git'
source 'https://github.com/hivecms/Specs.git'

target 'listview' do
    pod 'ListView', :path => "../ListView.podspec"
end
